name: Setup rust, clippy and rustfmt

description: |
  This action set up the Rust toolchain, including clippy and rustfmt with caching.

inputs:
  toolchain:
    description: "The toolchain to install."
    required: true
  target:
    description: "The target to install."
    required: true
  components:
    description: "The components to install."
    required: true
  rustflags:
    description: "The flags to pass to rustc."
    required: false
    default: "-Dwarnings"
  workspaces:
    description: "The workspaces to cache."
    required: false

runs:
  using: composite
  steps:
    - name: Generate Cache Key
      shell: bash
      run: |
        OS_ARCH="${{ runner.os }}-${{ runner.arch }}"
        echo "CACHE_KEY=${OS_ARCH,,}" >> "$GITHUB_ENV"

    - name: Setup rust
      uses: actions-rust-lang/setup-rust-toolchain@11df97af8e8102fd60b60a77dfbf58d40cd843b8 # v1.10.1
      with:
        toolchain: ${{ inputs.toolchain }}
        target: ${{ inputs.target }}
        components: ${{ inputs.components }}
        rustflags: ${{ inputs.rustflags }}
        cache: false

    - name: Setup Rust Caching
      uses: Swatinem/rust-cache@f0deed1e0edfc6a9be95417288c0e1099b1eeec3 # v2.7.7
      with:
        workspaces: ${{ inputs.workspaces }}
        prefix-key: v0-rust
        shared-key: ${{ env.CACHE_KEY }}
        cache-on-failure: false
        cache-targets: true
        cache-all-crates: false
        save-if: true
        cache-provider: github
