[package]
name = "kadeck-plugin-skeleton"
version = "0.1.0"
authors = ["danielhe4rt <danielhe4rt@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.215"
