[package]
name = "kadeck-plugin-test"
version = "0.1.0"
edition = "2021"

[dependencies]
libloading = "0.8.5"
kadeck-plugin-skeleton = { path = "../kadeck-plugin-skeleton", version = "*" }
tokio = { version = "1.41.1", features = ["full"] }
