name: CI - Rust

on:
  push:
    branches:
      - main
    paths:
      - "src-tauri/**"
  pull_request:
    branches:
      - main
    paths:
      - "src-tauri/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

defaults:
  run:
    working-directory: ./src-tauri

jobs:
  setup:
    name: Setup rust, clippy and rustfmt
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install required dependencies by Tauri
        uses: ./.github/actions/pre-setup-tauri

      - name: Setup rust
        uses: actions-rust-lang/setup-rust-toolchain@11df97af8e8102fd60b60a77dfbf58d40cd843b8 # v1.10.1
        with:
          toolchain: nightly
          target: x86_64-unknown-linux-gnu
          components: clippy, rustfmt
          rustflags: ${{ vars.BUILD_CONTINUE_ON_ERROR != 'true' && '-Dwarnings' || '' }}
          cache: false

      - name: lowercase the runner OS name
        shell: bash
        run: |
          OS=${{ runner.os }}
          echo "RUNNER_OS=${OS,,}" >> $GITHUB_ENV

      - name: Setup Rust Caching
        uses: Swatinem/rust-cache@82a92a6e8fbeee089604da2575dc567ae9ddeaab # v2.7.5
        with:
          workspaces: src-tauri
          prefix-key: v0-rust
          shared-key: ${{ env.RUNNER_OS }}-${{ runner.arch }}
          cache-on-failure: false
          cache-targets: true
          cache-all-crates: false
          save-if: true
          cache-provider: github

      - name: Build project
        run: make build

  lint:
    name: Perform lint
    runs-on: ubuntu-24.04
    needs:
      - setup
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install required dependencies by Tauri
        uses: ./.github/actions/pre-setup-tauri

      - name: Setup rust
        uses: actions-rust-lang/setup-rust-toolchain@11df97af8e8102fd60b60a77dfbf58d40cd843b8 # v1.10.1
        with:
          toolchain: nightly
          target: x86_64-unknown-linux-gnu
          components: clippy, rustfmt
          rustflags: ${{ vars.BUILD_CONTINUE_ON_ERROR != 'true' && '-Dwarnings' || '' }}
          cache: false

      - name: lowercase the runner OS name
        shell: bash
        run: |
          OS=${{ runner.os }}
          echo "RUNNER_OS=${OS,,}" >> $GITHUB_ENV

      - name: Setup Rust Caching
        uses: Swatinem/rust-cache@82a92a6e8fbeee089604da2575dc567ae9ddeaab # v2.7.5
        with:
          workspaces: src-tauri
          prefix-key: v0-rust
          shared-key: ${{ env.RUNNER_OS }}-${{ runner.arch }}
          cache-on-failure: false
          cache-targets: true
          cache-all-crates: false
          save-if: true
          cache-provider: github

      - name: Run linter
        continue-on-error: ${{ vars.BUILD_CONTINUE_ON_ERROR == 'true' }}
        uses: clechasseur/rs-clippy-check@50a0fd6f2f1a33307d603ee50d91eadbb2561120 # v3.0.6
        with:
          args: --all-features --no-deps
          working-directory: ./src-tauri

  format:
    name: Perform format
    runs-on: ubuntu-24.04
    needs:
      - setup
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install required dependencies by Tauri
        uses: ./.github/actions/pre-setup-tauri

      - name: Setup rust
        uses: actions-rust-lang/setup-rust-toolchain@11df97af8e8102fd60b60a77dfbf58d40cd843b8 # v1.10.1
        with:
          toolchain: nightly
          target: x86_64-unknown-linux-gnu
          components: clippy, rustfmt
          rustflags: ${{ vars.BUILD_CONTINUE_ON_ERROR != 'true' && '-Dwarnings' || '' }}
          cache: false

      - name: lowercase the runner OS name
        shell: bash
        run: |
          OS=${{ runner.os }}
          echo "RUNNER_OS=${OS,,}" >> $GITHUB_ENV

      - name: Setup Rust Caching
        uses: Swatinem/rust-cache@82a92a6e8fbeee089604da2575dc567ae9ddeaab # v2.7.5
        with:
          workspaces: src-tauri
          prefix-key: v0-rust
          shared-key: ${{ env.RUNNER_OS }}-${{ runner.arch }}
          cache-on-failure: false
          cache-targets: true
          cache-all-crates: false
          save-if: true
          cache-provider: github

      - name: Run formatter
        continue-on-error: ${{ vars.BUILD_CONTINUE_ON_ERROR == 'true' }}
        uses: actions-rust-lang/rustfmt@559aa3035a47390ba96088dffa783b5d26da9326 # v1.1.1
        with:
          manifest-path: ./src-tauri/Cargo.toml
